### ISSUE TITLE
analytics page

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/codefordc.github.com#141]
Using https://github.com/18F/analytics-reporter, we can show some stats for our main site and various projects.

This could be useful for people wondering about use cases and adoption for what we do, as well as monitoring the progress and health of projects.

**Comment by justgrimes** [comment]
might be a good idea to request that folks put their google analytics tracker id in their civic.json file (either as a custom metadata field or make it mandatory?)

**Comment by stvnrlly** [comment]
I'm not familiar enough with how Google Analytics work to know the best way to do this. However, I think the way it works is you have stock script that runs on each page you want to track, sending analytics data to a single tracker id. For example, all sites that feed analytics.usa.gov have to have https://analytics.usa.gov/dap/dap.min.js loaded on the page.

**Comment by mkalish** [comment]
I'm going to transition this ticket over to the project management page.
