### ISSUE TITLE
Expand projects page to include DC-oriented civic tech projects developed by other organizations

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/codefordc.github.com#173]

**Comment by stvnrlly** [comment]
I think that our list is creator-agnostic, and it would be great to promote more of the community. The biggest concern here is that people often consider the list to be "Things that I can find/work on at a meetup". If a project's maintainers won't be there or easily reachable in a way that we can support, it makes things awkward.

**Comment by mkalish** [comment]
@stvnrlly It looks like this one can be closed.
