### ISSUE TITLE
Two links are dead in the Readme

### ISSUE THREAD

**Issue by trycrmr** [codefordc/codefordc.github.com#181]
These two links are dead in the Readme.

> If you want to make a blog post: read this ( https://github.com/codefordc/guides/blob/master/codefordc-blog/make-a-blog-post.md ).

> If you want to add a project to the projects page: read this ( https://github.com/codefordc/guides/blob/master/start-a-project.md ).

**Comment by jayzmiles** [comment]
I've submitted a PR.
