### ISSUE TITLE
Category button on projects page is empty

### ISSUE THREAD

**Issue by ndanielsen** [codefordc/codefordc.github.com#200]
<img width="1224" alt="screen shot 2016-11-20 at 4 04 32 pm" src="https://cloud.githubusercontent.com/assets/2944777/20466144/650350a6-af3b-11e6-8bdf-b2a8ef85024a.png">

**Comment by stvnrlly** [comment]
Thanks for finding that! It looks like I missed updating that when the `civic.json` standard changed from "categories" to "tags". It should be fixed now via https://github.com/codefordc/codefordc.github.com/commit/114da123ce9afa3afe26a684c1013cefa3edc262.
