### ISSUE TITLE
Make separate page for 'Join slack'

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/codefordc.github.com#204]
As a project manager, I want to be able to link directly to where to tell project contributors to join the Code for DC Slack from within my project README or website. Currently, the join button is implemented only as a modal pop-up from the homepage. Make a separate page with the Join Slack form that is linked from the homepage. 

Bonus feature:
With this extra page, below the form, we could include a brief description of 'why slack' to help orient people that have never used the service.

**Comment by NealHumphrey** [comment]
@trycrmr or @mkalish you guys have opinions on this? I can do it with a PR if you guys are ok with the suggested change.

**Comment by mkalish** [comment]
Closed by #212

**Comment by NealHumphrey** [comment]
Cool I'll update our docs to link to this now!
